version: '3.9'

services:
  webforum.webforumapi:
    image: ${DOCKER_REGISTRY-}webforumwebforumapi
    build:
      context: .
      dockerfile: WebForum/Dockerfile
    networks:
     - webforum-network

networks:
   webforum-network: