version: '3.7'

services:
  webforum.webforumapi:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DATABASE_CONN: Server=db;Database=DBapi;User=sa;Password=sql_server1;
     # DATABASE_CONN: Host=db;Port=5432;Database=postgres;User Id=postgres;Password=postgres;
    ports:
      - "80"
    depends_on:
      - db 
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - webforum-network
  
  db:
    image: mcr.microsoft.com/mssql/server
    container_name: db_1
    environment:
      SA_PASSWORD: "sql_server1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - webforum-network
      
  #db-pgadmin:
  #  image: iovanb/dpadmin
   # environment:
    #  PGADMIN_DEFAULT_EMAIL: "iovan.barros@globalweb.com.br"
     # PGADMIN_DEFAULT_PASSWORD: "postgres"
   # ports:
   #   - "16543:80"
   # depends_on:
   #   - db
   # networks:
   #   - webforum-network
  
networks:
  webforum-network:

#volumes:
 # db-data:

